name: Deploy Multi Docker App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build test image
        run: docker build -t cosmin/react-test -f ./client/Dockerfile.dev ./client

      - name: Run tests
        run: docker run -e CI=true cosmin/react-test npm test

      - name: Build production images
        run: |
          docker build -t cosmin/multi-client ./client
          docker build -t cosmin/multi-nginx ./nginx
          docker build -t cosmin/multi-server ./server
          docker build -t cosmin/multi-worker ./worker