name: Deploy Multi Docker App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug secrets presence (temporar)
        run: |
              echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME != '' }}"
              echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD != '' }}"

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build test image
        run: docker build -t cosmin/react-test -f ./client/Dockerfile.dev ./client

      - name: Run tests
        run: docker run -e CI=true cosmin/react-test npm test

      - name: Build production images
        run: |
          docker build -t cosmin628/multi-client ./client
          docker build -t cosmin628/multi-nginx ./nginx
          docker build -t cosmin628/multi-server ./server
          docker build -t cosmin628/multi-worker ./worker

      - name: Push images to Docker Hub (Remote)
        run: |
          docker push cosmin628/multi-client
          docker push cosmin628/multi-nginx
          docker push cosmin628/multi-server
          docker push cosmin628/multi-worker